"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Shield, FileText, Lock, AlertCircle } from "lucide-react";

const TOS_ACCEPTED_KEY = "alecci_tos_accepted";

interface TosPopupProps {
  onAccept?: () => void;
}

export function TosPopup({ onAccept }: TosPopupProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isChecked, setIsChecked] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    // Check if ToS has been accepted
    const accepted = localStorage.getItem(TOS_ACCEPTED_KEY);
    if (!accepted) {
      setIsOpen(true);
    }
  }, []);

  const handleAccept = () => {
    if (!isChecked) return;

    localStorage.setItem(TOS_ACCEPTED_KEY, new Date().toISOString());
    setIsOpen(false);
    onAccept?.();
  };

  if (!mounted || !isOpen) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[100] flex items-center justify-center p-4"
        >
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-black/80 backdrop-blur-sm"
          />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ type: "spring", duration: 0.5 }}
            className="relative w-full max-w-2xl glass-dark rounded-2xl overflow-hidden"
          >
            {/* Gold accent line */}
            <div className="absolute top-0 left-0 right-0 h-1 red-gradient" />

            {/* Header */}
            <div className="p-6 pb-4 border-b border-white/10">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-xl bg-red-500/20">
                  <Shield className="size-6 text-red-400" />
                </div>
                <div>
                  <h2 className="text-xl font-semibold text-white">Terms of Service</h2>
                  <p className="text-sm text-muted-foreground">Please review and accept to continue</p>
                </div>
              </div>
            </div>

            {/* Content */}
            <ScrollArea className="h-[400px] p-6">
              <div className="space-y-6 text-sm text-foreground/80">
                {/* Key Points */}
                <section className="space-y-4">
                  <div className="flex items-start gap-3 p-4 rounded-xl bg-white/5 border border-white/10">
                    <FileText className="size-5 text-red-400 mt-0.5 shrink-0" />
                    <div>
                      <h3 className="font-medium text-white mb-1">Service Description</h3>
                      <p className="text-muted-foreground">
                        Alecci Media provides AI-powered strategic consulting through virtual executives
                        (Alexandria & Kim). Our service includes AI consulting, document generation,
                        voice interaction, and strategy templates.
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start gap-3 p-4 rounded-xl bg-white/5 border border-white/10">
                    <Lock className="size-5 text-red-400 mt-0.5 shrink-0" />
                    <div>
                      <h3 className="font-medium text-white mb-1">Data & Privacy</h3>
                      <p className="text-muted-foreground">
                        Your conversations and data are stored securely. We use industry-standard
                        encryption and never share your personal information with third parties
                        without your consent.
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start gap-3 p-4 rounded-xl bg-white/5 border border-white/10">
                    <AlertCircle className="size-5 text-red-400 mt-0.5 shrink-0" />
                    <div>
                      <h3 className="font-medium text-white mb-1">AI-Generated Content</h3>
                      <p className="text-muted-foreground">
                        Content generated by our AI executives is for informational purposes only.
                        While our AI provides strategic insights, you retain full ownership of
                        generated content and are responsible for verifying its accuracy.
                      </p>
                    </div>
                  </div>
                </section>

                {/* Full Terms Summary */}
                <section className="space-y-3">
                  <h3 className="font-medium text-white">Terms Summary</h3>
                  <ul className="space-y-2 text-muted-foreground">
                    <li className="flex items-start gap-2">
                      <span className="text-red-400 mt-1">•</span>
                      You must be at least 18 years old to use this service
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-red-400 mt-1">•</span>
                      You agree to use the service for lawful purposes only
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-red-400 mt-1">•</span>
                      We may update these terms with notice to users
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-red-400 mt-1">•</span>
                      AI recommendations should not replace professional advice
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-red-400 mt-1">•</span>
                      You can request data deletion at any time
                    </li>
                  </ul>
                </section>

                <p className="text-xs text-muted-foreground/60">
                  By accepting these terms, you acknowledge that you have read and understood our
                  full Terms of Service and Privacy Policy available on our website.
                </p>
              </div>
            </ScrollArea>

            {/* Footer */}
            <div className="p-6 pt-4 border-t border-white/10 space-y-4">
              <label className="flex items-center gap-3 cursor-pointer group">
                <Checkbox
                  checked={isChecked}
                  onCheckedChange={(checked) => setIsChecked(checked === true)}
                  className="border-red-500/50 data-[state=checked]:bg-red-500 data-[state=checked]:border-red-500"
                />
                <span className="text-sm text-foreground/80 group-hover:text-foreground transition-colors">
                  I have read and agree to the Terms of Service and Privacy Policy
                </span>
              </label>

              <Button
                onClick={handleAccept}
                disabled={!isChecked}
                className="w-full"
                size="lg"
              >
                Accept & Continue
              </Button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

export function useTosAccepted() {
  const [accepted, setAccepted] = useState<boolean | null>(null);

  useEffect(() => {
    const value = localStorage.getItem(TOS_ACCEPTED_KEY);
    setAccepted(!!value);
  }, []);

  return accepted;
}
