import { BOT_PERSONALITIES, type BotType } from "@/lib/bot-personalities";
import type { ChatMessage } from "@/lib/types";

/**
 * Export entire conversation to PDF
 */
export async function exportConversationToPDF(
  messages: ChatMessage[],
  chatTitle: string,
  botType: BotType,
): Promise<void> {
  const { default: html2canvas } = await import("html2canvas");
  const { default: jsPDF } = await import("jspdf");

  const personality = BOT_PERSONALITIES[botType];
  const date = new Date().toLocaleDateString();

  // Create container for rendering
  const container = document.createElement("div");
  container.style.cssText = `
    position: absolute;
    left: -9999px;
    width: 800px;
    padding: 40px;
    background: white;
    font-family: system-ui, -apple-system, sans-serif;
  `;

  // Build HTML content
  let html = `
    <div style="margin-bottom: 32px; padding-bottom: 20px; border-bottom: 2px solid #e5e5e5;">
      <div style="display: flex; align-items: center; gap: 16px; margin-bottom: 16px;">
        ${personality.avatar ? `<img src="${personality.avatar}" style="width: 64px; height: 64px; border-radius: 50%;" crossorigin="anonymous" />` : ""}
        <div>
          <h1 style="margin: 0; font-size: 24px; color: #1a1a1a;">${chatTitle}</h1>
          <p style="margin: 4px 0 0 0; color: #666; font-size: 14px;">
            Conversation with ${personality.name} • ${date}
          </p>
        </div>
      </div>
    </div>
  `;

  // Add messages
  for (const message of messages) {
    const isUser = message.role === "user";
    const textContent = message.parts
      ?.filter((part) => part.type === "text")
      .map((part) => part.text)
      .join("\n")
      .trim();

    if (!textContent) continue;

    const msgBotType = (message.metadata?.botType as BotType) || botType;
    const msgPersonality = BOT_PERSONALITIES[msgBotType];

    html += `
      <div style="margin-bottom: 24px; padding: 16px; border-radius: 12px; background: ${isUser ? "#f5f5f5" : "#fef2f2"};">
        <div style="font-weight: 600; font-size: 14px; color: ${isUser ? "#333" : "#b91c1c"}; margin-bottom: 8px;">
          ${isUser ? "You" : msgPersonality.name}
        </div>
        <div style="line-height: 1.6; white-space: pre-wrap; color: #1a1a1a; font-size: 14px;">
          ${escapeHtml(textContent)}
        </div>
      </div>
    `;
  }

  // Footer
  html += `
    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e5e5; color: #999; font-size: 12px; text-align: center;">
      Generated by Alecci Media AI • ${date}
    </div>
  `;

  container.innerHTML = html;
  document.body.appendChild(container);

  // Wait for images to load
  await new Promise((resolve) => setTimeout(resolve, 500));

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
    });

    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    const pdf = new jsPDF("p", "mm", "a4");
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(
      canvas.toDataURL("image/png"),
      "PNG",
      0,
      position,
      imgWidth,
      imgHeight,
    );
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(
        canvas.toDataURL("image/png"),
        "PNG",
        0,
        position,
        imgWidth,
        imgHeight,
      );
      heightLeft -= pageHeight;
    }

    const filename = `${personality.name.split(" ")[0]}-conversation-${new Date().toISOString().split("T")[0]}.pdf`;
    pdf.save(filename);
  } finally {
    document.body.removeChild(container);
  }
}

/**
 * Export entire conversation to Excel
 */
export async function exportConversationToExcel(
  messages: ChatMessage[],
  chatTitle: string,
  botType: BotType,
): Promise<void> {
  // Dynamic import to avoid SSR issues
  const ExcelJS = await import("exceljs");
  const personality = BOT_PERSONALITIES[botType];
  const date = new Date().toLocaleDateString();

  // Create workbook and worksheet
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Conversation");

  // Add header information
  worksheet.addRow(["Conversation Export"]);
  worksheet.addRow([`Title: ${chatTitle}`]);
  worksheet.addRow([`Executive: ${personality.name}`]);
  worksheet.addRow([`Date: ${date}`]);
  worksheet.addRow([]); // Empty row

  // Add column headers
  worksheet.addRow(["Role", "Speaker", "Message", "Timestamp"]);

  // Style header row
  const headerRowNum = 6;
  const headerRow = worksheet.getRow(headerRowNum);
  headerRow.font = { bold: true };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FFE0E0E0" },
  };

  // Set column widths
  worksheet.columns = [
    { key: "role", width: 12 },
    { key: "speaker", width: 20 },
    { key: "message", width: 80 },
    { key: "timestamp", width: 24 },
  ];

  // Add message data
  for (const message of messages) {
    const textContent = message.parts
      ?.filter((part) => part.type === "text")
      .map((part) => part.text)
      .join("\n")
      .trim();

    if (!textContent) continue;

    const isUser = message.role === "user";
    const msgBotType = (message.metadata?.botType as BotType) || botType;
    const msgPersonality = BOT_PERSONALITIES[msgBotType];

    // Use message metadata createdAt if available, fallback to current time
    const timestamp = message.metadata?.createdAt || new Date().toISOString();

    worksheet.addRow([
      message.role,
      isUser ? "You" : msgPersonality.name,
      textContent,
      timestamp,
    ]);
  }

  // Enable text wrapping for message column
  worksheet.getColumn(3).alignment = { wrapText: true, vertical: "top" };

  // Generate buffer and trigger download
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);

  const filename = `${personality.name.split(" ")[0]}-conversation-${new Date().toISOString().split("T")[0]}.xlsx`;
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
